# start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# re-number windows after deleting a window
set -g renumber-windows on

# enable mouse mode
set -g mouse on

# Use vim keybindings in copy mode
setw -g mode-keys vi

# status bar right
set -g status-right "%b %e, %I:%M %p "

# increase status text length
set -g status-left-length 100
set -g status-right-length 100

# status bar colors
set -g status-bg "#005f5f"
set -g status-fg "#a8a8a8"

# pane border colors 
set -g pane-border-style "fg=#1b3041"
set -g pane-active-border-style "bg=default,fg=#4e6374"

## Keybindings ##

# set new prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# split panes
bind | split-window -h
bind - split-window -v

# vim-like pane switching
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# pane resizing
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# move to last session
bind Z switch-client -l

# move to last active window
bind BSpace last-window

# swap panes
bind > swap-pane -D
bind < swap-pane -U

# Use Enter to copy selection to macOS clipboard
unbind -T copy-mode-vi Enter
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"

# Copy on mouse drag end
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# Enable macOS clipboard integration
set -g set-clipboard on

# reload configuration
bind R source-file ~/.tmux.conf

## Plugins ##

# tmux-resurrect
run-shell ~/.tmux/plugins/tmux-resurrect/resurrect.tmux
