# =============== Terminal =============== #

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-kitty:RGB"

# Allow Vim cursor shape to pass through tmux
set -as terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'


# =============== Windows / Panes =============== #

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Re-number windows after deleting a window
set -g renumber-windows on

# Enable mouse mode
set -g mouse on

# Use Vim keybindings in copy mode
setw -g mode-keys vi


# Status bar
set -g status-right "%b %e, %I:%M %p"
set -g status-left-length 100
set -g status-right-length 100
set -g status-style "bg=#005f5f,fg=#a8a8a8"

# Pane borders
set -g pane-border-style "fg=#1b3041"
set -g pane-active-border-style "bg=default,fg=#4e6374"


# =============== Keybindings =============== #

# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Split panes
bind | split-window -h
bind - split-window -v

# Vim-like pane switching
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Pane resizing
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# Last session
bind Z switch-client -l

# Last active window
bind BSpace last-window

# Swap panes
bind > swap-pane -D
bind < swap-pane -U


# =============== Clipboard =============== #

# Enter copies selection to macOS clipboard
unbind -T copy-mode-vi Enter
bind -T copy-mode-vi Enter \
    send-keys -X copy-pipe-and-cancel "pbcopy"

# Mouse selection copies to macOS clipboard
bind -T copy-mode-vi MouseDragEnd1Pane \
    send-keys -X copy-pipe-and-cancel "pbcopy"

# Enable tmux clipboard integration
set -g set-clipboard on

# Fix vim escape delay
set -sg escape-time 10


# =============== Reload =============== #

bind R source-file ~/.tmux.conf


# =============== Plugins =============== #

set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TPM
run '~/.tmux/plugins/tpm/tpm'
