tap "homebrew/bundle"

# CLI tools
brew "tmux"
brew "vim"
brew "starship"
brew "openjdk@17"
brew "ncdu"
brew "watchman"
brew "bat"
brew "procs"
brew "git-delta"
brew "eza"
brew "tree"
brew "fzf"
brew "ripgrep"
brew "fd"
brew "jq"
brew "yq"
brew "zoxide"
brew "fnm"
brew "pnpm"
brew "biome"
brew "wget"
brew "htop"

# Zsh
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"

# GUI applications
cask "kitty"
cask "google-chrome"
cask "android-studio"
cask "antigravity-ide"
cask "font-fira-code"
cask "dbeaver-community"