# vim:fileencoding=utf-8:foldmethod=marker

# =========================
# Font
# =========================

font_family      FiraCode Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 20.0

disable_ligatures never


# =========================
# Cursor
# =========================

#cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval 0.5

shell_integration enabled


# =========================
# Colors
# =========================

foreground              #d8dee9
background              #0f1117

selection_foreground    #ffffff
selection_background    #3b4252

cursor                  #88c0d0
cursor_text_color       background

url_color               #8fbcbb

active_border_color     #88c0d0
inactive_border_color   #2e3440

active_tab_foreground   #2e3440
active_tab_background   #88c0d0

inactive_tab_foreground #d8dee9
inactive_tab_background #1b1f27


# =========================
# Window
# =========================

window_padding_width 10

confirm_os_window_close 0

hide_window_decorations no

#background_opacity 0.96

#dynamic_background_opacity yes


# =========================
# Tabs
# =========================

tab_bar_edge top
tab_bar_style powerline

tab_powerline_style slanted

tab_title_template "{title}"


# =========================
# macOS
# =========================

macos_titlebar_color background
macos_option_as_alt yes
macos_quit_when_last_window_closed yes


# =========================
# Scrolling
# =========================

scrollback_lines 100000
wheel_scroll_multiplier 5.0


# =========================
# Performance
# =========================

repaint_delay 10
input_delay 3
sync_to_monitor yes


# =========================
# Clipboard
# =========================

copy_on_select yes


# =========================
# Terminal
# =========================

enable_audio_bell no
visual_bell_duration 0.0

remember_window_size yes

# term xterm-256color


# =========================
# Splits / Navigation
# =========================

map ctrl+shift+enter launch --location=hsplit
map ctrl+enter launch --location=vsplit

map ctrl+shift+h neighboring_window left
map ctrl+shift+j neighboring_window down
map ctrl+shift+k neighboring_window up
map ctrl+shift+l neighboring_window right

map ctrl+shift+[ previous_tab
map ctrl+shift+] next_tab


# =========================
# Open URLs
# =========================

open_url_with default


# =========================
# Startup
# =========================

shell .
