require("amit.colorscheme")
require("amit.statusline")
require("amit.highlights")
require("amit.commands")
require("amit.options")
require("amit.mappings")

require("amit.plugins")
require("amit.lspconfig")
require("amit.null_ls")
require("amit.completion")
require("amit.telescope")
require("amit.treesitter")

require("colorizer").setup()
require("gitsigns").setup()
require("nvim-surround").setup()
